const tags = {
	env:{title:'Miljö',icon:'🌳'},
	save:{title:'Besparing',icon:'💰'},
	ben:{title:'Förmån',icon:'😊'},
	promo:{title:'Företag anseende',icon:'🏆'},
	workplace:{title:'Attraktiv arbetsplats',icon:'❤️'},
	prod:{title:'Produktivitet',icon:'⚙️'},
	health:{title:'Hälsa',icon:'➕'},
};

const index = [
	{id:000,title:'Mindre utsläpp pga resor',tags:['env','promo']},
	{id:001,title:'Mycket sparad tid varje dag för anställda (restid, matlåda, kläder etc), lätt att spara 1h/dag eller mer om du bor längre bort)',tags:['ben']},
	{id:002,title:'Ostörd tid för att kunna fokusera bättre',tags:['ben','prod','save']},
	{id:003,title:'Attraktiv förmån för arbetsplats (hjälper att behålla och rekrytera anställda)',tags:['ben','promo','workplace']},
	{id:004,title:'Mindre smittrisk för sjukdomar om anställda inte känner press att komma till kontoret när de är krassliga',tags:['prod','save','health']},
	{id:005,title:'Mindre frånvaro om anställda kan jobba hemifrån när de känner sig lite krassliga',tags:['prod','health']},
	{id:006,title:'Mindre reskostnader för anställda',tags:['ben']},
	{id:007,title:'Möjlighet att laga färsk mat till lunch',tags:['ben','health']},
	{id:008,title:'Möjlighet till en bättre anpassad arbetsplats (ljud, ljus, temperatur, utrustning)',tags:['ben','workplace','health']},
	{id:009,title:'Möjlighet att rekrytera från större område',tags:['workplace','save','prod']},
	{id:010,title:'Lägre kostnad för underhåll av kontor (städning, slitage, reparationer etc)',tags:['save']},
	{id:011,title:'Lägre förbrukning för kontor (vatten, tvål, el, värme, kyla, kaffe etc)',tags:['save']},
	{id:012,title:'Möjlighet för anställda att göra mindre ärenden under dagen t ex ta emot paket, passa hantverkare, långkok etc',tags:['ben','workplace']},
	{id:013,title:'Uppmuntrar asynkron kommunikation som minskar avbrott och ökar produktivitet',tags:['prod']},
	{id:014,title:'Gladare personal med bättre livsbalans pga intjänad tid etc',tags:['ben','workplace','prod','health']},
	{id:015,title:'Mindre krav på klädsel (billigare och bekvämare)',tags:['ben','save']},
	{id:016,title:'Mindre förseningar pga trafik, väder, kollektivtrafik',tags:['prod','save','health']},
	{id:017,title:'Mindre uttröttande möten pga bekvämare sittplats, mindre social press etc',tags:['ben','health','prod']},
	{id:018,title:'Mindre risk att störa sig på kollegor pga ovanor, hög musik etc',tags:['ben','prod']},
	{id:019,title:'Möjligt att lyssna på musik utan hörlurar',tags:['ben','prod','health']},
	{id:020,title:'Hela arbetsstyrkan blir inte utslagen samtidigt vid ström/internet-avbrott, brandlarm eller liknande',tags:['prod','health']},
	{id:021,title:'Mindre krav på stora utrymmen för t ex parkering, möten och arbetsplatser',tags:['save']},
	{id:022,title:'Enklare att nå anställda när de inte har en stor byggnad att springa runt i',tags:['prod']},
	{id:023,title:'Lättare för handikappade eller folk med funktionsnedsättning/värk att jobba',tags:['prod','ben','promo','workplace']},
	{id:024,title:'Mindre risker för kontorsdrama, trakasserier, diskriminering etc',tags:['prod','ben','health']},
	{id:025,title:'Möjlighet att använda t ex en träningscykel under arbete utan att störa någon',tags:['health']},
	{id:026,title:'Möjlighet att sälja bilen och använda kollektivtrafik om tillräckligt mycket arbete kan göras hemifrån',tags:['ben','env','promo']},
	{id:027,title:'Möjlighet att trumma med fingrar, använda anti stress leksaker eller sjunga utan att störa någon',tags:['ben','health']},
	{id:028,title:'Mindre kö till toaletter, micros etc',tags:['prod','ben']},
	{id:029,title:'Mindre besvikelse från anställda som vant sig vid hemarbete under pandemin',tags:['ben','prod','promo']},
	{id:030,title:'Mer möjlighet till flexibilitet kring arbetstid (eftersom man redan är hemma är det t ex enklare att jobba lite längre om det krisar), större möjlighet att t ex täcka störe delen av dan med support tid',tags:['prod']},
	{id:031,title:'Enklare för introverta anställda att hålla sina "batteri" laddade',tags:['prod','health']},
	{id:032,title:'Möjligt att lyfta fram hemarbete för att visa att företaget tänker på miljön',tags:['env','promo']},
	{id:033,title:'Enklare att ta möte med externa parter utan att störa kollegor (kräver inte möteslokal och byte av arbetsplats)',tags:['prod','save']},
	{id:034,title:'Ingen oro att hinna hem i tid efter arbete (och mindre behov av att sluta tidigare)',tags:['prod','ben','health']},
	{id:035,title:'Möjlighet att använda egen bättre utrustning för jobb (skärmar, stol etc)',tags:['prod','ben','save']},
	{id:036,title:'Möjlighet att hyra ut delar av kontoret om inte alla är på plats samtidigt.',tags:['save']},
	{id:037,title:'Anställda kan spara in på t ex hundvakt/barnvakt',tags:['ben']},
	{id:038,title:'Anställda med lite äldre barn kan jobba även om barnet är sjukt (och minska risken att smitta övriga anställda)',tags:['prod','save','health']},
	{id:039,title:'Anställda kan undvika att ge sig ut i dåligt väglag och hamna i en olycka',tags:['prod','ben','health']},
	{id:040,title:'Mindre behov att köpa en dyrare mer central bostad',tags:['ben','health']},
	{id:041,title:'Lättare för anställda att dölja pinsamma medicinska problem',tags:['ben','health','prod']},
	{id:042,title:'Möjligt att jobba på vägen till semestermål och kunna njuta av en "längre" semester',tags:['ben','health','prod']},
	{id:043,title:'Möjligt att snabbt kunna hjälpa sin familj i akuta situationer',tags:['ben','health']},
	{id:044,title:'Möjligt att ta del av små viktiga händelser i sin familjs liv (e.g. barns första steg)',tags:['ben','health']},
	{id:045,title:'Möjligt att kunna använda lunchrasten till att göra lite hushålls sysslor så du har mer tid över efter jobbet',tags:['ben','health','prod']},
	{id:046,title:'Tillgång till sin egna privata toalett',tags:['ben','health']},
	{id:047,title:'Möjligt att jobba ute i friska luften, sommarstuga etc',tags:['ben','health','prod']},
	{id:048,title:'Möjligt att hålla koll på hemmet för att undvika brand, inbrott, läckor etc',tags:['ben']},
	{id:049,title:'Enkelt att ta en tupplur över lunchrasten',tags:['ben','health','prod']},
	{id:050,title:'Hjälp samhället att avlasta belastningen på vägarna',tags:['promo']},
	{id:051,title:'Lättare för anställda att vara punktliga när det bara är att trycka igång datorn för att vara redo',tags:['prod','ben']},
	{id:052,title:'Uppmuntrar anställda till att lära sig ny digital teknologi för samarbete som kan öka produktivitet både på plats och hemifrån',tags:['prod','ben']},
	{id:053,title:'Möjlighet till besparingar på utrustning om den anställde har egen utrustning hemma',tags:['save','env']},
	{id:054,title:'Minskad kostnad för transportskador på portabel utrustning',tags:['save','env']},
	{id:055,title:'Lättare att föra antecknignar och dubbelkolla uppgifter när du tar möten vid din arbetsstation',tags:['prod']},
];

const texts = {
	pageTitle: "Fördelar Med Hemarbete",
	furtherReading: "Vidare läsning",
	suggestions: "Lämna förslag eller rapportera problem",
	shareText: "Dela",
	shortUrl: "https://cutt.ly/Work-From-Home-Advantages-se",
}